FROM php:8.2-apache

# Install system dependencies including sqlite
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    libsqlite3-dev \
    sqlite3 \
    zip \
    unzip \
    && docker-php-ext-install zip pdo_mysql pdo_sqlite mbstring exif pcntl bcmath gd \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV APACHE_DOCUMENT_ROOT /var/www/html/public

RUN a2enmod rewrite
RUN mkdir -p ${APACHE_DOCUMENT_ROOT}

# Update Apache config
RUN sed -ri -e "s!/var/www/html!${APACHE_DOCUMENT_ROOT}!g" /etc/apache2/sites-available/*.conf

WORKDIR /var/www/html
COPY . .

# Set permissions
RUN chown -R www-data:www-data ${APACHE_DOCUMENT_ROOT} \
    /var/www/html/storage /var/www/html/bootstrap/cache

# Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN composer install --no-dev --optimize-autoloader

ENV PORT 80
RUN sed -i "s/Listen 80/Listen ${PORT}/" /etc/apache2/ports.conf
EXPOSE ${PORT}
CMD ["apache2-foreground"]
